#!/usr/bin/env bash
set -euo pipefail

BLUE='\033[0;34m'
LBLUE='\033[1;36m'
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

source ./devops/definitions.sh
source ./devops/ci/scripts/get-latest-version.sh

printf "${LBLUE}Restart docker-compose via ssh${NC}\n"

cfgPath=$SERVER_DEPLOY_PATH/devops/docker/docker-compose/production.yml

vars="export DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_PWD=$DOCKER_REGISTRY_PWD DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST HOSTNAME_PROD=$HOSTNAME_PROD APP_GROUP_CONFIG_PROD='$APP_GROUP_CONFIG_PROD' PORTAL_APP_SVC_PORT=$PORTAL_APP_SVC_PORT PORTAL_APP_SVC_DEBUG_PORT=$PORTAL_APP_SVC_DEBUG_PORT PORTAL_APP_SVC_HOST=$PORTAL_APP_SVC_HOST SHARED_APP_SVC_PORT=$SHARED_APP_SVC_PORT SHARED_APP_SVC_DEBUG_PORT=$SHARED_APP_SVC_DEBUG_PORT SHARED_APP_SVC_HOST=$SHARED_APP_SVC_HOST SKILLS_APP_SVC_PORT=$SKILLS_APP_SVC_PORT SKILLS_APP_SVC_DEBUG_PORT=$SKILLS_APP_SVC_DEBUG_PORT SKILLS_APP_SVC_HOST=$SKILLS_APP_SVC_HOST SKILLS_SVC_HOST=$SKILLS_SVC_HOST POSTGRES_USER=$POSTGRES_USER POSTGRES_PASSWORD=$POSTGRES_PASSWORD POSTGRES_PORT=$POSTGRES_PORT POSTGRES_HOST=$POSTGRES_HOST POSTGRES_DB=$POSTGRES_DB
;"

dockerCmd="
cd $SERVER_DEPLOY_PATH && \
./devops/ci/scripts/check-free-space.sh && \
docker-compose -f $cfgPath stop $CONTAINER_NAME && \
docker pull $IMAGE_NAME:$VERSION && \
docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:latest && \
docker-compose -f $cfgPath up --remove-orphans -d $CONTAINER_NAME
"

cmd="$vars $dockerCmd"

echo $cmd

ssh "gitlab-runner@$HOSTNAME_PROD" $cmd

printf " ${LBLUE}All steps completed${NC}\n"

